export const LOAD_PERSONAL_DETAILS ='LOAD_PERSONAL_DETAILS';
export const  START = '_START';
export const  SUCCESS = '_SUCCESS';
export const  FAIL = '_FAIL';
export const CHANGING_CURRENT_BUTTON = 'CHANGING_CURRENT_BUTTON';
export const CHANGING_NUMBER_PROFILES_ON_PAGE = 'CHANGING_NUMBER_PROFILES_ON_PAGE';
export const SORTING_PERSONAL_DETAILS = 'SORTING_PERSONAL_DETAILS';



